// <auto-generated />
using System;
using GestionDepot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDepot.Migrations
{
    [DbContext(typeof(GestionDBContext))]
    [Migration("20240527061636_initial migration211221112")]
    partial class initialmigration211221112
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionDepot.Models.BonEntree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<int?>("IdChambre")
                        .HasColumnType("int");

                    b.Property<int?>("IdFournisseur")
                        .HasColumnType("int");

                    b.Property<int?>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<decimal>("Qte")
                        .HasColumnType("decimal(16,3)");

                    b.HasKey("Id");

                    b.HasIndex("IdChambre");

                    b.HasIndex("IdFournisseur");

                    b.HasIndex("IdProduit");

                    b.HasIndex("IdSociete");

                    b.ToTable("BonEntrees");
                });

            modelBuilder.Entity("GestionDepot.Models.Chambre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdSociete");

                    b.ToTable("Chambres");
                });

            modelBuilder.Entity("GestionDepot.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cin")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("IdSociete");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GestionDepot.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdSociete");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("GestionDepot.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdSociete")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdSociete");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("GestionDepot.Models.Societe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MF")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Societes");
                });

            modelBuilder.Entity("GestionDepot.Models.BonEntree", b =>
                {
                    b.HasOne("GestionDepot.Models.Chambre", "Chambre")
                        .WithMany()
                        .HasForeignKey("IdChambre");

                    b.HasOne("GestionDepot.Models.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("IdFournisseur");

                    b.HasOne("GestionDepot.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit");

                    b.HasOne("GestionDepot.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete");

                    b.Navigation("Chambre");

                    b.Navigation("Fournisseur");

                    b.Navigation("Produit");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("GestionDepot.Models.Chambre", b =>
                {
                    b.HasOne("GestionDepot.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("GestionDepot.Models.Client", b =>
                {
                    b.HasOne("GestionDepot.Models.Societe", "Societe")
                        .WithMany("Clients")
                        .HasForeignKey("IdSociete");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("GestionDepot.Models.Fournisseur", b =>
                {
                    b.HasOne("GestionDepot.Models.Societe", "Societe")
                        .WithMany("Fournisseurs")
                        .HasForeignKey("IdSociete");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("GestionDepot.Models.Produit", b =>
                {
                    b.HasOne("GestionDepot.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("GestionDepot.Models.Societe", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Fournisseurs");
                });
#pragma warning restore 612, 618
        }
    }
}
